VaibhavArora314/StyleShare

- .github/workflows/close-old-issue.yml
Fixes #16 
@VaibhavArora314 @Ultimateutkarsh11 please review and merge this PR
Also, please add labels and assign me this PR
Thank You!
> added workflow as per issue #16

- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
#39 
#43
Added Code of Conduct file to the project.
Added PR Template
> Created CODE_OF_CONDUCT.md and PR_TEMPLATE.md

- frontend/src/pages/Posts.tsx
**Description**
This pull request introduces one new feature to the application:
1. **Dynamic Search**: without reloading the page, I had created a state called searchQuery in Posts.tsx in which I applied filter method and at search input I am targeting the setsearchQuery . So, at every key press it will update the state.
2. **Enhanced User Experience**: With this feature, users can find their respective posts more quickly, improving the overall performance and reliability of the web app without stressing the backend.
**Overview**
1.  Search by Author
2. Search by Title 
3. Search by Description
> feat: Added Dynamic search Bar in the posts section successfully issue 38

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Footer.tsx
- frontend/src/pages/About.tsx
- frontend/src/pages/ContactUs.tsx
- frontend/src/pages/Policy.tsx
Made changes in footer.
Modified and added links in footer.
Fixes #48 
Added links and redirected them to corresponding pages. The user profile link will redirect to user profile if logged in else redirect to sign in page.
Please check it and let me know if any changes to be made, Thank you.
> Made changes in footer

- backend/.env.example
- backend/package-lock.json
- backend/package.json
- frontend/src/pages/Profile.tsx
The profile page was enhanced.
**Issue #55 Fixed**
https://github.com/VaibhavArora314/StyleShare/assets/114602603/32c3cacb-0024-4bfe-af29-9de9bd53b925
> Profile page improved

- frontend/src/App.tsx
- frontend/src/components/GoTop.tsx
Scroll to top
fixed : #95 
changes made:
GoTop.tsx created in components
app.tsx
> Scroll to top

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Post.tsx
1.  Used five social media platform, Telegram, X, WhatsApp, LinkedIn, Facebook.
2.  User just have to go to the post which they want to share by clicking any social media btn a window pop and all the content is ready for you just have to press POST that's it.
3.  The content has the post url and a text "👋 Hey ! I found amazing tailwind css 💅 component {post.title} have a look, The design is done by {post.author.username} check out the link it's amazing 😀".
Fixes #114 
New feature: Added Social media sharing.
1.  Telegram:
2.  X:
and similarly for rest of the apps...
> feat: Added Share the post on social media platform feature Successfully issue 114

- frontend/src/pages/About.tsx
Changed Some Text Colour in About Us page to white to make it more visible
Changed Some Text Colour in About Us page to white to make it more visible
Fixes - #133 
Added styling as "text-white"
Footer
> About Us Page Text Colour Changed

- frontend/src/App.tsx
- frontend/src/components/ScrollToTop.tsx
- frontend/src/components/ScrollToTopWhenRouteChanges.tsx
Fixed the bug of pages rendering at bottom
Solved issue #141 
- [ x] I have tested the changes locally
- [ x] Changes are backward-compatible
https://github.com/VaibhavArora314/StyleShare/assets/154724111/7733d40d-2cf7-48d3-947d-50c3f23995cb
> Fixed the bug of pages rendering at bottom

- frontend/src/components/Navbar.tsx
Improving the current navbar to make it look more _stylish_
Fixes: https://github.com/VaibhavArora314/StyleShare/issues/130
added logo to navbar, changed font, certain classes, etc
https://github.com/VaibhavArora314/StyleShare/assets/128628820/b3d2fa51-1b38-4e30-8a9b-713f005a9b93
> fix: improve navbar

- frontend/src/App.css
- frontend/src/components/Footer.tsx
Show Hover effects on footer's Github and Home icons.
Added Hover effect in github and Home icons in footer.
issue no #164 
In footer.tsx change add className so i can use that for give className.
In App.css added styles for that.
> Hover effects added in footer's icons

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TestimonialSlider.tsx
- frontend/src/pages/Home.tsx
added Testimonials
added Testimonials
Fixes : #192 
added new file in components folder
TestimonialSlider.tsx
made some changes in home.tsx
> testimonials

- frontend/index.html
- frontend/package-lock.json
- frontend/src/index.css
Custom Cursor
Custom cursor added to the website.
#191
I have added custom interactive cursor.
Footer
> custom cursor added (issue 191)

- frontend/src/components/CodeEditor.tsx
- frontend/src/components/Navbar.tsx
Adding copy in code editor
Adding copy in code editor
Fixed: #210 
1.codeeditor.tsx
> Adding copy in code editor

- frontend/src/components/Navbar.tsx
changed Navbar  to new version 
changed Navbar  to new version 
fixes: #229 
1. navbar.tsx
> changed Navbar  to new version 

- backend/prisma/schema.prisma
- backend/src/routes/post/controller.ts
- backend/src/routes/post/route.ts
- frontend/src/App.css
- frontend/src/components/PostCard.tsx
- frontend/src/components/ReactionButtons.tsx
- frontend/src/hooks/usePost.tsx
- frontend/src/pages/Post.tsx
- frontend/src/types.ts
1. Removed the like/dislike routes and controllers from the backend and created a fresh 4 api's for reactions.
2. API's are reactToPostController,removeReactionController, getUserReaction, getAllreaction and their respective routes. 
3. In frontend, I created ReactionButtons.tsx which post and get the reaction which allow user to do reactions.
4. In PostCard I fetched all the reaction by all the users and sum it up to show total and the emoji will show only one time each.
5. I created five emoji exactly like linkedin also ~ same colors => 'Like' | 'Celebrate' | 'Support' | 'Love' | 'Insightful' | 'Funny'.
6. The design is simple and easy to use by any user.
7. User most be a verified user and also logged In to the application.
8. By default if user click on button it will trigger like …
> feat: Combined the feature of like/dislike with the reaction feature successfully issue 252

- frontend/src/components/Footer.tsx
**Pull Request**
**Title**
Add hover effect to footer links
**Description**
This pull request introduces hover effects to the footer links, changing their color to blue (#2563EB) when hovered over. This enhancement improves the user experience by providing visual feedback on interactive elements.
**Related Issues**
Fixes #160
**Changes Made**
Added CSS classes to change the link color to blue (#2563EB) on hover.
**Checklist** 
**Screenshots**
> added_hover_effect

- frontend/src/App.css
- frontend/src/index.css
1.  This PR changes the color of both cursor and scrollbar.
2.  Also, the width is changed of scrollbar and the cursor is rounded now.
3.  Looks nice and matches the theme of the webapp.
Fixes #227 
New features: Cursor and scrollbar css changed.
> feat: Cursor and scrollbar css changed successfully issue 227

- frontend/src/components/Features.tsx
issue no #257
Add scale effects on What we offer to developers Cards
Added style in tailwind css
Fixes #257
Just added tailwind css for get hover effects.
> Card hover effect added

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/PostCodeWithPreview.tsx
- frontend/src/pages/Post.tsx
1.  Downloaded the npm packages npm install jszip file-saver which help in convert to zip and save to the user system.
2.  User have to login to download the code.
3.  Both code i.e html as well as js is compressed in the zip.
4.  Changes is done in Post.js for download and in PostCodeWithPreview for css.
Fixes #196 
New features: Added Download as zip button feature.
> feat: Added Download as zip button feature successfully issue 196

- frontend/src/components/GoTop.tsx
- frontend/src/styles/goTop.css
- package-lock.json
Add animation to scroll to top button
Add floating to and down animation to scroll to top button
Fixes #262 
Added a custom css file to styles and added those css class names to scroll to top button.
Footer
> Scroll-to-top animation added

- frontend/src/components/Showcase.tsx
issue no #276
Add hover effects on cards.
Hover effects to life cards in y direction up side.
Fixes #276 
Added tailwind css.
> Hover effects on cards added in Our code editor section

- frontend/src/components/Navbar.tsx
[Bug] : Menu bar Close icon implement
- In this project Menu bar close icon can be implemented.
Fixes : #288 
bug fixes 
[Screencast from 2024-06-25 08-18-31.webm](https://github.com/VaibhavArora314/StyleShare/assets/121082414/b56d8175-5b08-4bc7-8ed0-8461614a1ba2)
[Screencast from 2024-06-24 07-10-49.webm](https://github.com/VaibhavArora314/StyleShare/assets/121082414/9e00fb69-1dd1-4940-adf1-5097c4508eaa)
> [Bug] :` Menu bar` Close icon implement

- frontend/src/components/PostCard.tsx
Added follow option in postcard itself
Added follow option in postcard itself
fixes: #291 
Footer
> Added follow option in postcard itself

- frontend/src/components/ui/MagicButton.tsx
Add hover effects on explore now button
Just added some scale and y direction some transition that give better hover effect.
Fixes #290 
Feat
https://www.loom.com/share/79e08bdc28b9445da5dce43cb476aea3
> Added Scale and hover effects in Explore button

- frontend/src/components/Showcase.tsx
Changed Home Page code editor Section to responsive
Changed Home Page code editor Section to responsive
fixes: #282 
please check in preview
Footer
> Changed Home Page code editor Section to responsive

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Footer.tsx
Link added to logo in footer
I added the link to logo to divert it to main screen when in footer the logo is clicked
#296 
Footer
> Link added to logo in footer

- frontend/src/components/PostCard.tsx
1.  Did icons size to 23.
2.  Added button tag for uniformness.
Fixes #323 
New features: Fixed buttons sizes and it's positions.
> feat: Fixed buttons sizes and it's positions successfully issue 323

- frontend/src/components/PostCard.tsx
1. With the help of Post.tsx component I implemented this favorite/unfavorite feature in PostCard.tsx.
2. The design is responsive and I used flex for this.
3. Now user can mark fav/unfav from seeing the card only instead of going inside the Post.
Fixes #237 
New features:  Added favorite button in PostCard.
> feat: Added favorite button in PostCard successfully issue 237

- frontend/src/App.css
Add hover effects on scrollbar thumb
I have added hover on thumb also added cursor pointer.
Fixes #310
Just added hover effects code.
> Added Hover on scrollbar thumb

- frontend/src/components/FAQ.tsx
Make effect when one hover on FAQ's question
Just add hover color like light purple
Fixes #313 
Feature
> Hover on faq quation added

- frontend/src/pages/Posts.tsx
1.  I used flex box and did justify between so that it divides it in two component like in one side filter, show trending button and on other side there is a search bar.
2.  The design is responsive in all devices respectively.
Fixes #336 
New features: Added responsiveness in posts page.
> Feat: Added responsiveness in posts page successfully issue 336

- admin/src/components/CaptchaAdmin.tsx
- admin/src/pages/Signin.tsx
- frontend/src/components/CaptchaUser.tsx
- frontend/src/pages/Signin.tsx
- frontend/src/pages/Signup.tsx
1.  Created Captcha files for users and admin.
2.  Managing the state with useState and calling the captcha component in user login and register also in admin login respectively.
3.  The Design is responsive and work in both light/dark mode.
Fixes #356 
New features: Added captcha in every authentication pages.
> Feat: Added captcha in every authentication pages successfully issue 356

- admin/src/components/StatusCard.tsx
- backend/src/routes/admin/controller.ts
- backend/src/routes/admin/route.ts
1.  I created a controller and route for getting the total counts for totalUsers, totalPosts, totalComments, totalReactions, messages, favorites.
2.  And I am fetching it in the StatusCard.
3.  I had used appropriate icons for the cards.
4.  Here the messages are those which are sended from the contact us form. 
Fixes #365 
New features: Creating API/fetching in card status.
> Feat: Creating API/fetching in card status successfully Issue 365

- admin/index.html
- admin/src/components/SideBar.tsx
- admin/src/pages/Dashboard.tsx
- admin/src/pages/PageNotFound.tsx
- admin/src/pages/Posts.tsx
- admin/src/pages/Profile.tsx
- admin/src/pages/Signin.tsx
- admin/src/pages/Users.tsx
1. In admin frontend, with the document.title I added the all the necessary name on every tab.
2.  Also add favicon on the admin panel.
Fixes #416 
New features:  Added favicon and title on every tab.
> Feat: Added favicon and title on every tab successfully issue 416

- frontend/src/pages/Favorite.tsx
1. Fixed the margin top of the favorite posts page by doing css changes in the favoriteposts.tsx file.
2. The design is responsive and work in both light/dark mode.
Fixes #415 
Bug fixes: Fixed the margin in favorite posts page.
> Bug: Fixed the margin in favorite posts page successfully issue 415

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/PostCodeWindow.tsx
1. With the help of the highlight.js package this feature is achieved.
2.  The code is modified in codepreview page.
Fixes #80 
New features: Added syntax highlight for html and javascript in post page.
> Feat: Added syntax highlight for html and javascript in post page successfully issue 80

- frontend/src/components/Navbar.tsx
1. I removed the span and replaced it with the Link.
2. Also removed the Link from the languageDropdown.
Fixes #446 
Bug fixes: Fixed nav  logo link with dropdown.
> Bug: Fixed nav  logo link with dropdown successfully issue 446

- README.md
#460
Adding markdown features
Added a go to top button also Added markdown features like clear headers will enhance readability and make it easier for users to navigate.
#460
Footer
> Updated Added markdown features README.md

- frontend/package-lock.json
- frontend/src/pages/About.tsx
Add loading when scroll effects on about page's true marks.
Added Effect like Home page right tick text in about's how it works section text.
Fixes #451
Added Effects in About Page
https://www.loom.com/share/e07e8e5c0f9b42e1bd71d36e98c0ba39
> Added Effect in How it Works

- admin/src/App.tsx
- admin/src/components/GoogleTranslate.tsx
- admin/src/components/Layout.tsx
- admin/src/components/Navbar.tsx
- admin/src/components/SideBar.tsx
- admin/src/components/UpdatePost.tsx
- admin/src/pages/Comments.tsx
- admin/src/pages/ContactMessages.tsx
- admin/src/pages/Dashboard.tsx
- admin/src/pages/Graphs.tsx
- admin/src/pages/Posts.tsx
- admin/src/pages/Profile.tsx
- admin/src/pages/Users.tsx
- admin/src/styles/Translate.css
1. In admin, I created a GoogleTranslator file and imported it in SideBar also created .css file for it also,
2. I created a Sidebar Layout so that instead of calling side bar in each component I will call it only in App.tsx file and the whole app will use that.
3. Also the logout will not show the sidebar, only login person can see that.
4. The design is responsive.
Fixes #364 
New feature: Added Google translator in admin panel.
> Feat: Added Google translator in admin panel successfully issue 364

- frontend/src/App.tsx
- frontend/src/components/ProgressScrollDown.tsx
1. I created a Progress component and with the help of window. I am doing this.
2. Imported in the App.tsx so, that it appears on every screens.
3. No External package is used.
4. The design is responsive.
Fixes #469 
New feature: Added scroll down progress in style share.
> Feat: Added scroll down progress in style share successfully issue 469

- admin/src/components/UpdatePost.tsx
1. In admin, I removed the loading... instead I added the ColorRing loader in UpdatePost.
Fixes #472 
New feature: Added loader in update post by admin page.
> Feat: Added loader in update post by admin page successfully issue 472

- frontend/src/components/GoogleTranslate.tsx
- frontend/src/styles/Translate.css
Hide Select language after some scroll.
Just Hide Select Language after some scroll.
Fixes #479
Feat
https://www.loom.com/share/27e629a02cef4057a8189efc8528d287
> Select Language hide after some scroll

- frontend/src/components/PostCard.tsx
1. In frontend, I fixed the link with the Link and in place of Read more i am displaying the reactions.
Fixes #487 
Bug fixes: Fixed Card height is disrupted and made it uniform.
> Bug: Fixed Card height is disrupted and made it uniform successfully issue 487

- frontend/src/pages/Policy.tsx
1. In frontend, with the help of -margin I fixed the  extra margin between policy page and navbar.
Fixes #486 
Bug fixe: Fixed the extra margin between policy page and navbar.
> Bug: Fixed the extra margin between policy page and navbar successfully issue 486

- frontend/src/pages/Profile.tsx
- frontend/src/pages/ShowProfile.tsx
1. In frontend, with the help of the translate y I created this hover effect.
2. The design is responsive and works in light/dark mode.
Fixes #485 
New feature: Added hover effect on user profile social icons.
> Feat: Added hover effect on user profile social icons successfuly issue 485

- backend/src/routes/post/controller.ts
- backend/src/routes/post/route.ts
- frontend/src/components/PostCard.tsx
1. In backend, I created the favorite-status controller and routes to track the post and user favorite status.
2. In frontend, I call the api and map with post card and removed the local storage.
3. I tried in different account with the same account and It is working perfectly.
Fixes #497 
Bug fixe: Added favorite/unfavorite status for user and removed local storage for favorite feature.
https://github.com/user-attachments/assets/d854564a-6577-43db-989d-56030e303339
> Bug: Added favorite/unfavorite status for user and removed local storage for favorite feature successfully issue 497

- admin/src/App.tsx
- admin/src/components/SideBar.tsx
- admin/src/pages/Favorites.tsx
- admin/src/types.ts
- backend/src/routes/admin/controller.ts
- backend/src/routes/admin/route.ts
1. In backend, I created the controller and routes for fetching the favorite posts by users.
2. In admin, I created a interface for favorite posts and created Favorites.tsx in which i am fecrhing the above api in the table.
Fixes #500 
New feature: Added showing admin which user marked favorite to which post.
> Feat: Added showing admin which user marked favorite to which post successfully issue 500

- frontend/src/pages/LeaderBoard.tsx
1. In frontend, I used useNavigate hook to redirect because if we user Link it will destroy the table css.
Fixes #404 
New feature: Redirect to user profile on click of entire row in leaderboard.
> Feat: Redirect to user profile on click of entire row in leaderboard successfully issue 404

- frontend/src/pages/Contributors.tsx
1. In frontend, I created a state for currentPage and created perPage to 9.
2. With JS with the help of array I am traversing the pages accordingly.
Fixes #519 
New feature: Added pagination in contributors page.
> Feat: Added pagination in contributors page successfully issue 519

- backend/prisma/schema.prisma
- backend/src/routes/user/controller.ts
- backend/src/routes/user/route.ts
- frontend/src/components/FeedbackForm.tsx
- frontend/src/pages/Profile.tsx
1. In backend, I created a prisma model which contains the feeback and number of star and link with the user model.
2. Also created the controller and routes for the same to post the feedback by the user.
3. In frontend, Adjacent to edit button i created a Rate us button when click opens a model which consists of stars and the feedback textarea when click on submit the post api is hit.
4. The design is responsive.
Fixes #513 
New feature: Added feedback feature in style share.
https://github.com/user-attachments/assets/58c16a97-4b23-4772-8cc3-062a718c8c1c
> Feat: Added feedback feature in style share successfully issue 513

- frontend/src/components/Navbar.tsx
- package-lock.json
fixes #516 
Relocated signIn and signUp buttons to the right side of the navbar
changed the CSS of div containing the signIn and signUp buttons
- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible
> sinup_signin_relocated

- frontend/src/components/TestimonialSlider.tsx
Added borders to testimonials. Issue number #484
Added borders for testimonials in boht light and dark mode for better readability and appearance.
Fixes #484
Added some tailwind classes for borders.
Footer
> Added borders to testimonials. Issue number #484

- frontend/src/pages/ContactUs.tsx
Not Proper margin in contact form in bottom. 
Just added proper margin bottom for contact section.
Fixes #545
> Added Margin Bottom for contact section

- admin/src/pages/ContactMessages.tsx
- backend/src/routes/admin/controller.ts
- backend/src/routes/admin/route.ts
1. In backend, I created a route and controller for creating the delete message feature.
2. In admin, I created the button delete in which i am calling the api for deleting the message.
Fixes #575 
New feature: Added contact messages delete feature for admin.
https://github.com/user-attachments/assets/d8c18f10-2f4f-4341-a79e-c7305c42d9c1
> Feat: Added contact messages delete feature for admin successfully issue 575

- frontend/src/components/Navbar.tsx
1. In frontend, with the help of tailwind gap i added the space between the nav links.
Fixes #584 
Bug fix: Fixed Navbar gap at x axis.
> Bug: Fixed Navbar gap at x axis successfully issue 584

- frontend/src/pages/Posts.tsx
Fixed the posts card for tablet screen to fix overflow of content outside the card
Fixes #587 
Card grid for all sizes
> Fixed posts card for tablet size 768px

- frontend/src/components/Navbar.tsx
1. In frontend, with the help of flexbox i added the icons and made navbar perfect.
Fixes #311 
New feature: Added Icons in the navbar and fix some navbar bugs and structure.
> Feat: Added Icons in the navbar and fix some navbar bugs and structure successfully issue 311

- backend/src/routes/post/controller.ts
1. By utilizing the .replace method in JavaScript, I effectively cleaned the code outputs.
2. CSS Code: The initial code output contained the prefix ```html and a trailing ```. The .replace method was used to remove these unwanted symbols, resulting in a cleaner and more user-friendly code output.
3. JavaScript Code: Similarly, the JavaScript output included the ```javascript prefix and the trailing ```. This was also addressed using the .replace method, ensuring that the JavaScript code is returned without extraneous characters.
4. This solution significantly improves the usability of the code outputs, enabling users to easily copy, customize, and implement the provided code without any unnecessary clutter.
Fixes #600 
Bug fixes: Unnecessary text and symbols in code output for HTML and …
> Bug: Unnecessary text and symbols in code output for HTML and javaScript in gemini successfully issue 600
