VaibhavArora314/StyleShare

frontend/src/pages/Posts.tsx
Resolves issue #12 
Image for reference:
Do tell me if I need to change anything.
=> Add filter option in posts

frontend/src/pages/Home.tsx, frontend/src/pages/Posts.tsx
=> Hover effect in Post cards

backend/src/routes/post/controller.ts, backend/src/routes/post/route.ts, frontend/src/pages/Posts.tsx
1. I had created a hook name currentPage and setcurrentPage which will change the number of posts with the const postsPerPage = 9.
2. I had created handlePreviousPage which will decrement by - 1 and handleNextPage which will increment by + 1 per posts.
3. In backend I had created an api with function getPostsWithPagination which basically do 3 tasks with variables skip, take, select as with pageSize 12.
Fixes #40 
New feature introduced as pagination in posts page.
=> feat: Added Pagination for posts section with backend api successfully Issue 40

frontend/src/App.tsx, frontend/src/components/Navbar.tsx, frontend/src/index.css, frontend/tailwind.config.js
updated navbar  with  gradient,hover effects  on sign in and sign up and changed the font of "style share"
Footer
=> Feature/enhance navbar:Updated Navbar

frontend/src/components/PostCard.tsx, frontend/src/pages/Posts.tsx
Closes #41 
I have removed all the conflicts.
=> removed merge conflicts #41

backend/src/routes/post/controller.ts, frontend/package-lock.json, frontend/src/pages/Post.tsx
Removed the user email from the post details page and added a back button on it for better navigation
For security reasons, the email displayed at the bottom of the post details page is removed.
N/A
Mentioned above
N/A
N/A
Footer
=>  removed user email from post details page  #47

frontend/src/components/Navbar.tsx
Hamburger close automatically
Added closeMenu when user click on any menu the closeMenu is trigered and its close the menu
#45 
closeMenu function added 
https://github.com/VaibhavArora314/StyleShare/assets/140513098/298cdcc8-e94e-4a02-97ba-9dc6b3f18764
=> Hamburger automatically close when user click on any menu

backend/prisma/schema.prisma, backend/src/routes/post/controller.ts, backend/src/routes/post/route.ts, frontend/package-lock.json, frontend/package.json, frontend/src/pages/Comment.tsx, frontend/src/pages/Post.tsx, frontend/src/types.ts
1.  Created comment section in frontend as well as backend.
2.  Created Prisma schema, controllers, routes in backend.
3.  Created Comment file and added in Post file.
4.  API fetch and Posting comment is implemented.
5.  Responsive design.
Fixes #116 
New feature: Comment section .
https://github.com/VaibhavArora314/StyleShare/assets/120380073/baa6cb47-22ce-48f2-819e-7394ba421ca4
=> feat: Community Interaction with comment section added successfully Issue 116

backend/prisma/schema.prisma, backend/src/routes/post/controller.ts, backend/src/routes/post/route.ts, frontend/src/App.tsx, frontend/src/components/Navbar.tsx, frontend/src/pages/Favorite.tsx, frontend/src/pages/Post.tsx, frontend/src/types.ts
1.   In backend: I created a new prisma schema for storing fav/unfav posts in database.
2.   Also created routes and controller for 3 operations, -Favorite -Unfavorite -FetchFavorite posts respectively.
3.   In Frontend fetch and posting operation is done, new file is created called Favorite where all fav posts are fetched.
4.   By clicking heart icon user can fav/unfav a post.
Fixes #123 
New features: Adding mark components as favorites/unfavorities.
https://github.com/VaibhavArora314/StyleShare/assets/120380073/817a29d3-7105-4fbd-b183-a5090722b053
=> feat: Added mark components as favorites and unfavorites feature successfully issue 123

frontend/src/pages/Signin.tsx, package-lock.json
Improved error handling for login failures by adding a default error message to ensure toast notifications and state updates always display a meaningful message.
Improved Error Handling for Login Failures 
Enhanced error handling to ensure meaningful error messages are always displayed during login failures. A default error message is now shown if the backend does not provide one.
Fixes #158 
1. Added a default error message for login failures.
2. Ensured toast notifications always display a meaningful message.
3. Updated state to accurately reflect the error message. 
Footer
=> Corrected Toast  Fictionality

frontend/src/components/HeroText.tsx, frontend/src/components/ui/TypeWriter.tsx, frontend/src/styles/hero.css
Fixed hero sizing for mobile screen 
Fixed to have a proper sizing on mobile screen and the typing effect.
Fixes #190 
changed the sizing of text in typing effect to keep inside the screen for small screen size.
Footer
=> fixed sizing for mobile screen

frontend/src/components/HeroText.tsx, frontend/src/pages/Home.tsx
[Bug]: Text "Style Share" Not Displaying Correctly in Hero Section
This pull request addresses the issue of the text "Style Share" not displaying correctly in the hero section. The changes made ensure that the text is properly visible and aligned as intended.
Fixes #178 
- Fixed the CSS styling for the "Style Share" text to ensure proper display and alignment.
- Adjusted the font size and color to match the design specifications.
- Updated the HTML structure for better responsiveness.
Before
After
Footer
=> Solved issue 178

frontend/src/components/EditPost.tsx, frontend/src/components/Navbar.tsx
1.  Instead of md device I shifted the responsiveness to lg devices in tailwind classes to achieve responsive design.
2.  This PR is free from conflicts and new packages and ready to merge.
Fixes #205 
New features: Navbar responsiveness fixed.
=> feat: Navbar responsiveness fixed successfully Issue 205 

frontend/package-lock.json, frontend/package.json, frontend/src/components/CodeEditorAndPreview.tsx, frontend/src/components/PostCodeWithPreview.tsx, frontend/src/components/PostPreview.tsx, frontend/src/pages/EditPost.tsx, frontend/src/pages/NewPost.tsx
Added Preview mode while creating a new post or updating a current one
This will allow the user to confirm whether their code works when adding a new post or updating an existing one. 
N.A.
A new component for the text area fields and the preview section was added. 
Additionally, a toggle button was added for the user to switch between editing and previewing the code.
Finally, a toast was added if the user clicked on the text editor during preview mode.
N.A.
N.A.
Footer
=> feat: Preview feature added in new and edit post functionality (issue #180)

frontend/src/components/Features.tsx
Hover on y direction up side added.
Just added tailwind css to that 4 cards.
Added tailwind effects for y direction hover.
https://www.loom.com/share/23d5fbd90fac43e6b786a1b65052e063
=> Hover added on cards to y direction up side

frontend/src/pages/CodeEditor.tsx, frontend/src/pages/ContactUs.tsx, frontend/src/pages/CustomizeWithAi.tsx, frontend/src/pages/EditPost.tsx, frontend/src/pages/Favorite.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/LeaderBoard.tsx, frontend/src/pages/NewPost.tsx, frontend/src/pages/PageNotFound.tsx, frontend/src/pages/Policy.tsx, frontend/src/pages/Post.tsx, frontend/src/pages/Posts.tsx, frontend/src/pages/Profile.tsx, frontend/src/pages/ShowProfile.tsx, frontend/src/pages/Signin.tsx, frontend/src/pages/Signup.tsx, frontend/src/pages/TrendingPosts.tsx
1. I put the tab name on every possible places with the help of document.title feature.
2. With this user can see the tabs information easily and navigate seamlessly across the platform.
3. Used emoji's and fun text to make it interactive and user friendly.
Fixes #321 
New features: Added route name on every tab.
1. Home Page 
2. Posts Page
3. Leaderboard
and similarly for the rest of them.
=> feat: Added route name on every tab successfully Issue 321

backend/prisma/schema.prisma, backend/src/middleware/adminAuth.ts, backend/src/routes/admin/controller.ts, backend/src/routes/admin/route.ts, backend/src/routes/admin/zodSchema.ts, backend/src/routes/index.ts
1. In backend, In prisma at user add new field i.e isAdmin: bool, In routes created admin folder in that i created controllers for adminLogin and fetching admin profile with adminAuth middleware.
2. Created routes for both and created zodSchema for admin.
3. Api is tested in postman and in thunder client and is working fine.
Fixes #343 
New features: Added admin login logic in backend.
=> feat: Added admin login logic in backend successfully issue 343

frontend/src/components/TestimonialSlider.tsx
Buttons very close to screen give it proper margins
Add proper margins for every screen like lg ,md and sm.
Fixes #332
Just added tailwind css for margins
=> Fix Next/Previous button distance for all size screen

frontend/src/components/Footer.tsx
In footer's github and home icon not have same radius when we hover on that. 
Add same radius property add github icon from github now both looks similar hover effects.
Fixes #333 
Bug
=> Fix hover radius and added Githubicon from react-icons

frontend/src/pages/LeaderBoard.tsx
In mobile screen Leaderboard full table is cuts need to scroll in x direction 
Added tailwind css for make it responsive.
Fixes #359
=> Leaderboard fix for small screen

frontend/src/App.tsx, frontend/src/components/Footer.tsx, frontend/src/pages/Contributors.tsx
Solved issue #372 
- [ x] I have tested the changes locally
- [ x] Changes are backward-compatible
https://github.com/VaibhavArora314/StyleShare/assets/154724111/bdc73e38-35d4-416f-b2f9-fd74c2294355
=> Added contributors page

frontend/src/components/Navbar.tsx
In mobile screen navbar section sing in/sing up and mode change button not have proper margin
Added margins when mobile menu is open.
Fixes #353
Added style for margins
=> Fix mobile menu

frontend/src/pages/Policy.tsx
In Privacy Policy, Terms and Conditions, Cookie Policy image takes lots of space in left side. 
Fix image like 
Privacy Policy (image as a symbol)
Added hover scale on that image for user feel.
By this save space wasting in left side and get better view in small screen.
Fixes #383 
Change position of image and style.
**In small size screen looks great now**
=> Fix image to stop wasting of space

frontend/src/pages/Contributors.tsx
Contibutor github profile link is on image so user can't understand that make github link seperate.
Add one p tag in that add link and remove link from image.
Fixes #418
Add one p tag in that add link and remove link from image.
=> Added Github link in Contributor

admin/src/pages/PageNotFound.tsx, frontend/src/App.tsx, frontend/src/pages/PageNotFound.tsx
1. In frontend as well as in admin the Page not found text is visible in light/dark mode, by changing the css for dark theme.
Fixes #429 
Bug fixes: Fixed the page not found text in light/dark mode.
=> Bug: Fixed the page not found text in light/dark mode successfully issue 429

admin/src/components/NewPosts.tsx, admin/src/components/SideBar.tsx, admin/src/components/StatusCard.tsx, admin/src/components/TrendingPosts.tsx
1. Changed the css of the buttons.
2. Added Router link in the table and cards.
3. Design is responsive.
Fixes #439 
New feature: Added link to table and card in admin dashboard.
=> Feat: Added link to table and card in admin dashboard successfully issue 439

admin/package-lock.json, admin/package.json, admin/src/components/NewPosts.tsx, admin/src/components/StatusCard.tsx, admin/src/components/TrendingPosts.tsx, admin/src/pages/ContactMessages.tsx, admin/src/pages/Graphs.tsx, admin/src/pages/Posts.tsx, admin/src/pages/Users.tsx
1. With help of react skeleton loader I had applied the lazy loading in Status cards of admin.
2. With the help of react spinners I had applied the Circle ring loader in all the tables.
3.  The design is responsive.
Fixes #438 
New features: Added lazy loading for cards and loader for tables in admin panel.
https://github.com/user-attachments/assets/fe833f6b-29ae-45f4-8cdc-856f09cbe930
=> Feat: Added lazy loading for cards and loader for tables in admin panel successfully issue 438

frontend/src/pages/ContactUs.tsx
Add tilt effects on contact form images.
As Per Suggestion Instead of tilt add a little horizontal movement on hover.
Fixes #450 
Add Tailwind Properties for better and smooth hover effects.
https://www.loom.com/share/347ad239e89b47af9e22f69d4248ccf7
=> Hover added on contact form image

README.md
#455 
enhanced the readme
added feature in sec, table of content linked codeofconduct.md and contributing.md in main readme file creating separate sections
#455 
- [x ] Documentation has been updated (if necessary)
Footer
=> Enhanced the documentation

frontend/src/App.tsx, frontend/src/components/Navbar.tsx, frontend/src/styles/Translate.css
1.  I Changed the whole navbar and specially the added the user image and below it there is a dropdown like most of the webapps have nowadays.
2.  The design is responsive in all the devices and can work in both light/dark mode.
3.  Removed the white space also.
4.  Add google translator in fixed positon.
5.  If added in navbar it will lead to problem.
Bug fixes: Modified the whole navbar and adjust the google translator button. 
=> Bug: Modified the whole navbar and adjust the google translator button successfully issue 462

backend/prisma/schema.prisma, backend/src/routes/user/controller.ts, backend/src/routes/user/zodSchema.ts, frontend/src/components/profileForm.tsx, frontend/src/pages/Profile.tsx, frontend/src/pages/ShowProfile.tsx, frontend/src/types.ts
1.  In backend, I modified the user prisma schema and also updated the updateUserProfile controller as well as userProfileController and showUserProfileController to fetch the social links and their profiles.
2.  In frontend, I added the field for Twitter, facebook, github, linkedin and portfolio social links.
3.  Also modified the show user profile to see other profile section.
4.  Used icons which are responsive and also work in light/dark mode.
Fixes #226 
New feature:  Added social media links to user profile section.
https://github.com/user-attachments/assets/fc84533b-8d82-4ca2-a9eb-4d57c69fa78e
=> Feat: Added social media links to user profile section successfully issue 226

frontend/package-lock.json, frontend/src/components/PostCard.tsx
Make the postcard clickable.
When we hover over the card, it appears as though we can click anywhere on it, and clicking takes us straight to the read more page.
Fixes #350 
Make the postcard clickable
[Screencast from 22-07-24 10:53:56 PM IST.webm](https://github.com/user-attachments/assets/dc149c86-cba5-4975-a9a9-855aa1c5e77b)
By submitting this pull request, I attest that I have complied with the applicable code of conduct and supplied the necessary screenshot for verification.
=> FIX: Make the post card clickable

frontend/src/components/SharePostButtons.tsx
Hover
Added the Hovering effect on socials
Feat: #502 
https://github.com/user-attachments/assets/e7cdc534-d139-47c5-9f03-177f928d422e
Footer
=> Feat #502 added hovering effect on socials

frontend/src/components/PostCard.tsx
Fixes the Like button in the postcard
We do not want to be redirected to the read more page when we are liking the post card, and vice versa. Instead, we only want to like the post itself.
closes #503 
The react mouse event was only added after the file (PostCard.tsx) was modified.
[Screencast from 25-07-24 02:47:24 PM IST.webm](https://github.com/user-attachments/assets/cdceab8b-78f3-40d0-ad60-a106d1f26c7e)
Footer
=> Fixes the Like button in the postcard

admin/src/pages/Comments.tsx, admin/src/pages/Posts.tsx
1. In admin, I added the flex and margin bottom to give the margin bottom to the tables.
Fixes #498 
Bug fix: Fixed margin bottom in all tables in admin panel.
=> Bug: Fixed margin bottom in all tables in admin panel successfully issue 498

admin/src/App.tsx, admin/src/components/SideBar.tsx, admin/src/pages/Reactions.tsx, admin/src/types.ts, backend/src/routes/admin/controller.ts, backend/src/routes/admin/route.ts
1. In backend, in admin I created the controller and routes to fetch all the user with their reactions, post and creation date.
2. In admin, I created the reaction interface and created a new file as Reactions.tsx in this I am fetching the user reactions from the api which I created.
Fixes #499 
New feature: Added showing admin which user reacted to which post.
=> Feat: Added showing admin which user reacted to which post successfully issue 499

admin/src/components/NewPosts.tsx, admin/src/components/SideBar.tsx, backend/package-lock.json, backend/package.json, backend/src/routes/admin/controller.ts, backend/src/routes/admin/route.ts
1. In backend, I created a controller and routes for that I used PDFKIT for styling the PDF and download it.
2. In admin, I added the button which download the pdf in admin system.
Fixes #501 
New feature: Download all the stats in pdf for admin.
=> Feat: Download all the stats in pdf for admin successfully Issue 501

frontend/src/components/FAQ.tsx
Added the hover to open FAQ answer
Fixes #518 
FAQ compoenent
https://github.com/user-attachments/assets/13dfe007-d353-4c18-b304-cf77f2f6c152
Footer
=> Added the hover to open FAQ answer feature

frontend/src/components/FAQ.tsx
Fixed the FAQ for mobile screen 
Made it look good for mobile screen
Fixes #517 
Footer
=> Fixed the FAQ section for mobile screen

backend/src/routes/user/controller.ts, backend/src/routes/user/route.ts, frontend/src/components/TestimonialSlider.tsx
1. In backend, I created a route and controller to get all the feedback from the database.
2. In frontend, I get the api in the Testimonial section.
Fixes #526 
New feature: Integrated the feedback with the Testimonial in style share.
=> Feat: Integrated the feedback with the Testimonial in style share successfully issue 526

frontend/src/components/Footer.tsx, frontend/src/pages/Policy.tsx
Hey @VaibhavArora314 , @akbatra567 and @Ultimateutkarsh11 
issue closes #538 
I have added the MIT License navigating link in the footer.
Please take a look - 
https://github.com/user-attachments/assets/cb19b20e-50f3-427c-a8ea-e1cee0512724
Footer
=> ✔️Added MIT License in Footer

frontend/src/components/FAQ.tsx, frontend/src/pages/Comment.tsx, frontend/src/pages/HomePagePosts.tsx, frontend/src/pages/LoginForm.tsx
1. In frontend, I used the dark for changing the titles, showing navyblue in light mode and white in dark mode.
2. The design isresponsive.
Fixes #537 
Bug fixe:  Fixed title in ligh/dark mode.
=> Bug: Fixed title in ligh/dark mode successfully issue 537

frontend/src/components/Features.tsx
Add Scale on image. 
Added Lazy loading and scale on image when hover on it.
Fixes #544
https://www.loom.com/share/8eb293e8b9944935929d09d82a2da782
=> Added Scale and Lazy loading

admin/src/App.tsx, admin/src/components/SideBar.tsx, admin/src/pages/UsersFeedbacks.tsx, admin/src/types.ts, backend/prisma/schema.prisma, backend/src/routes/admin/controller.ts, backend/src/routes/admin/route.ts, backend/src/routes/user/controller.ts
1. In backend, I created a new field in prisma as visible:false, and also created a controller and routes for the admin to get all the feedback and also updating the visiblility.
2. In Style share main page if visibility: false then no feeback is show else it will show according to admin.
3. In admin, I created a coponent name as UserFeedback in which I am fetching all the feedbacks and with button click admin can set visible:true/false respectively.
4. Also I created interface for the feedback.
5. The design is responsive.
Fixes #547 
New feature: Added Feedback/Testimonial  control in admin panel.
https://github.com/user-attachments/assets/86132236-87e5-429e-90be-acd88ea6a349
I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for …
=> Feat: Added Feedback/Testimonial  control in admin panel successfully issue 547

frontend/src/pages/Posts.tsx
Added press Enter to search functionality in posts page
Previously, in posts section, while searching for a post we have to click on "search" button to search for a specific keyword post.
I added functionality so that, we can directly type our keyword and hit "ENTER" to search, thus improving user experience.
Fixes #549 
Added a key event in searchbox which is triggered when ENTER key is pressed, calling the "handleSubmit" function which then takes care of fetching relevant posts.
https://github.com/user-attachments/assets/b79db1b5-bf74-4520-af0f-2298eded0829
Footer
Thanks for assigning me this issue.
=> Added Enter to search functionality in posts page

backend/.env.example, frontend/src/components/Navbar.tsx
fixes #535  
improved the UI of right side of the navbar
improves height/width of the components along with padding
- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible
Footer
=> Improved right side of the navbar 

frontend/src/components/TestimonialSlider.tsx, frontend/src/types.ts
1. In frontend, I created a separate interface in types.tsx for managing all the interface in single place.
2. The code is reduced in the Testimonials section also using rating I am fetching the user ratings.
3. I modified the Testimonial design.
4. The design is responsive.
Fixes #566 
New feature: Showing users ratings in Testimonials and also using best coding practices.
=> Feat: Showing users ratings in Testimonials and also using best coding practices successfully issue 566 

frontend/src/App.tsx, frontend/src/pages/Policy.tsx
1. For ScrollBar, I included the App.css because it is included previously.
2. In frontend, added some padding and adjust the id to solve this bug.
Fixes #569 
Bug fixe: Fixed footer nav links and also restored the scrollbar.
=> Bug: Fixed footer nav links and also restored the scrollbar successfully issue 569

admin/Dockerfile, backend/Dockerfile, docker-compose.yml, frontend/Dockerfile
This pr adds docker-compose.yaml at the root of the project
fixes #564 
- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
Footer
=> Add docker compose file to the root of the project

frontend/package-lock.json, frontend/package.json, frontend/src/components/PostsSkeleton.tsx, frontend/src/pages/Posts.tsx
Added for both dark and light mode
Created skeleton component for posts
Footer
=> Added skeleton for posts loading

frontend/package-lock.json, frontend/package.json, frontend/src/components/LeaderboardSkeleton.tsx, frontend/src/pages/LeaderBoard.tsx
Leader board skeleton loader
Loader for both dark and light mode
#578 
Created skeleton
Footer
=> Added skeleton loader for leaderboard

admin/src/pages/UsersFeedbacks.tsx, backend/src/routes/admin/controller.ts, backend/src/routes/admin/route.ts
1. In backend, I created a route and controller for creating the delete feedback feature.
2. In admin, I created the button delete in which i am calling the api for deleting the feedback.
Fixes #576
New feature: Added delete users feedback feature for admin.
https://github.com/user-attachments/assets/a1412c7d-9a83-4d81-9301-6a8ccf8fb2e8
=> Feat: Added delete users feedback feature for admin successfully issue 576

frontend/src/components/PostCard.tsx
1. In frontend, I am calling the status code for favorite when user is login only.
2. Because of this the api is never hit when other users hit the page.
Fixes #570 
Bug fixe: Fixed fetch favorite post status code.
=> Bug: Fixed fetch favorite post status code successfully issue 570

backend/src/routes/post/controller.ts, frontend/src/hooks/usePosts.tsx, frontend/src/pages/Posts.tsx
Users can now sort posts by reactions or date posted, with the ability to toggle between ascending and descending order by selecting the same option.
Enhanced the user search experience by introducing a "Sort by" option, allowing users to toggle between ascending and descending order.
N/A
Added two additional parameters to the backend API call and updated the UI to include the dropdown for sorting options.
N.A.
N.A.
Footer
=> added a sort by option on the posts page

frontend/src/components/PostCodeWindow.tsx
Fixed the code page text sizing for smaller screen and code window
Fixes #595  #589 
Footer
=> Fixed the code page sizings or text and windows

frontend/src/components/CodeSkeleton.tsx, frontend/src/pages/Post.tsx
Added the skeleton loader for code page
Fixes #588
=> Added skeleton laoder for code page

backend/src/routes/post/controller.ts, backend/src/routes/post/route.ts, frontend/src/App.tsx, frontend/src/hooks/usePosts.tsx, frontend/src/pages/Posts.tsx
1. In backend, I created the route and controller for getting searchQuery and suggest to user.
2. In frontend, I am fetching the api in the usePosts and then calling the function in the Posts component.
3. While writing on the search bar with the help of ul the user can see the dropdown and click on any it will see that posts.
4. The design is responive and work in both light/dark mode respectively.
Fixes #586 
New feature: Added post search suggestion when search on searchbar.
https://github.com/user-attachments/assets/efa1c7d5-b06f-419d-90c0-44acb37dbcd7
=> Feat: Added post search suggestion when search on searchbar successfully issue 586
